export const LOAD_SHOTS = "LOAD_SHOTS"
export const CLEAR = "CLEAR"
export const SET_RADIUS = "SET_RADIUS"
export const SET_ERROR_MESSAGE = "SET_ERROR"
export const REMOVE_ERROR_MESSAGE = "REMOVE_ERROR"
export const SET_TOTAL_RECORDS = "SET_TOTAL_RECORDS"
export const SET_OFFSET = "SET_OFFSET"